# -*- coding: utf-8 -*-
"""PomidoruśAI_improved (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOUlrxqMEkil9UhmWNqLA2d8jK5_fHH6
"""

!pip install opendatasets -q

import opendatasets as od
import os
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import EfficientNetB0
import matplotlib.pyplot as plt
import numpy as np

print("TF version:", tf.__version__)

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    tf.config.experimental.set_memory_growth(gpus[0], True)

od.download("https://www.kaggle.com/datasets/ashishmotwani/tomato")
print("Download complete")

"""## 1. Dataset loading"""

BATCH_SIZE = 32
IMAGE_SIZE = (224, 224)
AUTOTUNE = tf.data.AUTOTUNE

TRAIN_DIR = "tomato/train"
VALID_DIR = "tomato/valid"

train_ds_raw = tf.keras.utils.image_dataset_from_directory(
    TRAIN_DIR,
    labels="inferred",
    label_mode="int",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=123
)

base_val_ds_val = tf.keras.utils.image_dataset_from_directory(
    VALID_DIR,
    labels="inferred",
    label_mode="int",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    validation_split=0.5,
    subset="training",
    seed=42
)

base_val_ds_test = tf.keras.utils.image_dataset_from_directory(
    VALID_DIR,
    labels="inferred",
    label_mode="int",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    validation_split=0.5,
    subset="validation",
    seed=42
)

val_ds  = base_val_ds_val.cache().prefetch(AUTOTUNE)
test_ds = base_val_ds_test.cache().prefetch(AUTOTUNE)

class_names = train_ds_raw.class_names
NUM_CLASSES = len(class_names)

print("--- DATASET SPLIT ---")
print(f"Train batches : {tf.data.experimental.cardinality(train_ds_raw).numpy()}")
print(f"Val   batches : {tf.data.experimental.cardinality(val_ds).numpy()}")
print(f"Test  batches : {tf.data.experimental.cardinality(test_ds).numpy()}")
print(f"\nClasses ({NUM_CLASSES}):")
for i, n in enumerate(class_names):
    print(f"  {i:2d}: {n}")

def verify_dataset(ds, name):
    class_counts = {}
    total_images = 0

    for images, labels in ds:
        total_images += images.shape[0]
        for label in labels.numpy():
            class_counts[class_names[label]] = class_counts.get(class_names[label], 0) + 1

    print(f"\n--- {name} ---")
    print(f"Total images : {total_images}")
    print(f"Classes found: {len(class_counts)}/{NUM_CLASSES}")
    for cls in class_names:
        count = class_counts.get(cls, 0)
        flag = "⚠️  MISSING" if count == 0 else ""
        print(f"  {cls:<40} {count:>5}  {flag}")

verify_dataset(val_ds,  "Validation Set")
verify_dataset(test_ds, "Test Set")
verify_dataset(train_ds_raw, "Train Set")

"""## 2. Augmentation pipeline

RandomFlip / Rotation / Zoom

RandomBrightness

RandomContrast

RandomTranslation
"""

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.1),
    layers.RandomBrightness(0.2),
    layers.RandomContrast(0.2),
    layers.RandomTranslation(0.1, 0.1),
], name="augmentation")

# EfficientNetB0 has its own built-in preprocessing
train_ds = (train_ds_raw
            .map(lambda x, y: (data_augmentation(x, training=True), y),
                 num_parallel_calls=AUTOTUNE)
            .prefetch(AUTOTUNE))

val_ds  = val_ds.cache().prefetch(AUTOTUNE)
test_ds = test_ds.cache().prefetch(AUTOTUNE)

"""## 3. Model — EfficientNetB0 with transfer learning

**Two-phase training strategy:**

1. **Phase 1** — freeze the entire base; only train the new head. The base weights are fragile at first; training the head alone lets it stabilise before we touch the base.
2. **Phase 2** — unfreeze the top 30 layers of the base and fine-tune with a small learning rate. The top layers learn disease-specific features while the bottom layers (generic edges) stay mostly frozen.
"""

def build_model(num_classes, input_shape=(224, 224, 3)):
    inputs = tf.keras.Input(shape=input_shape)

    base_model = EfficientNetB0(
        include_top=False,
        weights="imagenet",
        input_tensor=inputs
    )
    base_model.trainable = False

    x = layers.Rescaling(1./255)(base_model.output)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    return tf.keras.Model(inputs, outputs), base_model

model, base_model = build_model(NUM_CLASSES)
model.summary()

"""## 4. Phase 1 - train the head only

We use a relatively high learning rate here because only the new dense layers are updating; the pretrained weights are frozen and safe.
"""

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_accuracy",
    patience=7,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=3,
    min_lr=1e-7,
    verbose=1
)

# Phase 1 compile

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("Phase 1: training head only (base frozen)")
history_phase1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    callbacks=[early_stopping, reduce_lr]
)

"""## 5. Phase 2 - unfreeze and fine-tune"""

base_model.trainable = True

total_layers = len(base_model.layers)
fine_tune_from = total_layers - 30

for layer in base_model.layers[:fine_tune_from]:
    layer.trainable = False

trainable_count = sum(1 for l in base_model.layers if l.trainable)
print(f"Fine-tuning {trainable_count} of {total_layers} base layers")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

early_stopping_phase2 = tf.keras.callbacks.EarlyStopping(
    monitor="val_accuracy",
    patience=7,
    restore_best_weights=True,
    verbose=1
)

print("\nPhase 2: fine-tuning top 30 layers")
history_phase2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=[early_stopping_phase2, reduce_lr]
)

"""## 6. Results - combined training curves"""

def plot_history(h1, h2):
    acc1  = h1.history["accuracy"]
    vacc1 = h1.history["val_accuracy"]
    acc2  = h2.history["accuracy"]
    vacc2 = h2.history["val_accuracy"]
    loss1  = h1.history["loss"]
    vloss1 = h1.history["val_loss"]
    loss2  = h2.history["loss"]
    vloss2 = h2.history["val_loss"]

    acc   = acc1 + acc2
    vacc  = vacc1 + vacc2
    loss  = loss1 + loss2
    vloss = vloss1 + vloss2
    epochs = range(len(acc))
    split  = len(acc1)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    for ax, y, vy, title, ylabel in [
        (axes[0], acc,  vacc,  "Accuracy",     "Accuracy"),
        (axes[1], loss, vloss, "Loss Function", "Loss"),
    ]:
        ax.plot(epochs, y,  label="Train",      color="steelblue", linewidth=2)
        ax.plot(epochs, vy, label="Validation", color="orange",    linewidth=2)
        ax.axvline(split, color="gray", linestyle="--", alpha=0.6, label="Phase 2 starts")
        ax.set_title(title, fontsize=12)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.legend()
        ax.grid(True, linestyle="--", alpha=0.5)

    plt.tight_layout()
    plt.show()

    best_val = max(vacc)
    print(f"\nBest validation accuracy: {best_val:.4f} ({best_val*100:.1f}%)")

plot_history(history_phase1, history_phase2)

"""## 7. Evaluation on test set"""

test_loss, test_acc = model.evaluate(test_ds, verbose=1)
print(f"\nTest accuracy : {test_acc:.4f} ({test_acc*100:.1f}%)")
print(f"Test loss     : {test_loss:.4f}")

from sklearn.metrics import confusion_matrix, classification_report
import itertools

y_true, y_pred = [], []
for images, labels in test_ds:
    preds = model.predict(images, verbose=0)
    y_pred.extend(np.argmax(preds, axis=1))
    y_true.extend(labels.numpy())

print(classification_report(y_true, y_pred, target_names=class_names, digits=3))

# Plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(12, 10))
plt.imshow(cm, interpolation="nearest", cmap="Blues")
plt.colorbar()
tick_marks = np.arange(NUM_CLASSES)
plt.xticks(tick_marks, class_names, rotation=45, ha="right", fontsize=8)
plt.yticks(tick_marks, class_names, fontsize=8)
plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.title("Confusion Matrix — Test Set")

# Annotate cells
thresh = cm.max() / 2.
for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
    plt.text(j, i, str(cm[i, j]), horizontalalignment="center",
             color="white" if cm[i, j] > thresh else "black", fontsize=7)

plt.tight_layout()
plt.show()

model.save("tomato_disease_efficientnetb0.keras")
print("Model saved!")